
admin_login:
    path:      /login
    defaults:  { _controller: MatrixAdminBundle:Login:index }


admin_home:
    path:     /
    defaults: { _controller: MatrixAdminBundle:Index:index }

distributor_list:
    path:     /dist
    defaults: { _controller: MatrixAdminBundle:Index:index }

licenses_list:
    path:     /lic
    defaults: { _controller: MatrixAdminBundle:Licenses:index }

distributor_form:
    path:     /dist/create
    defaults: { _controller: MatrixAdminBundle:Distributors:createForm }
    methods: GET

distributor_create:
    path:     /dist/create
    defaults: { _controller: MatrixAdminBundle:Distributors:create }
    methods: POST



#List of all Account Owners(Companies)
distributors_companies:
    path:     /comp
    defaults: { _controller: MatrixAdminBundle:Distributor:companies }


#DISTRIBUTOR
#Create new Account Owner(Company)
account_owner_form:
    path:     /owner/create
    defaults: { _controller: MatrixAdminBundle:Distributor:createAccountOwnerForm }
    methods: GET

account_owner_create:
    path:     /owner/create
    defaults: { _controller: MatrixAdminBundle:Distributor:createAccountOwner }
    methods: POST

#List of Account Owners created by this Distributor
account_owner_list:
    path:     /dist/owners
    defaults: { _controller: MatrixAdminBundle:Distributor:getAccountOwners }

#Licenses of this Distributor
distributors_licenses:
    path:     /dist/lic
    defaults: { _controller: MatrixAdminBundle:Licenses:getByDistributor }

#ACCOUNT OWNER
#Managers list
managers_list:
    path:     /owner/managers
    defaults: { _controller: MatrixAdminBundle:AccountOwner:getManagers }

#Create new Manager
manager_form:
    path:     /manager/create
    defaults: { _controller: MatrixAdminBundle:AccountOwner:createManagerForm }
    methods: GET

manager_create:
    path:     /manager/create
    defaults: { _controller: MatrixAdminBundle:AccountOwner:createManager }
    methods: POST

#MANAGER
#Mobile Users list
mobile_users_list:
    path:     /manager/users
    defaults: { _controller: MatrixAdminBundle:Manager:getMobileUsers }

#Create new Mobile User
mobile_user_form:
    path:     /muser/create
    defaults: { _controller: MatrixAdminBundle:Manager:createMobileUserForm }
    methods: GET

mobile_user_create:
    path:     /muser/create
    defaults: { _controller: MatrixAdminBundle:Manager:createMobileUser }
    methods: POST

#Departments list
departments_list:
    path:     /manager/departments
    defaults: { _controller: MatrixAdminBundle:Manager:getDepartments }

#Create new Department
department_form:
    path:     /department/create
    defaults: { _controller: MatrixAdminBundle:Manager:createDepartmentForm }
    methods: GET

department_create:
    path:     /department/create
    defaults: { _controller: MatrixAdminBundle:Manager:createDepartment }
    methods: POST

#Plants list
plants_list:
    path:     /manager/plants
    defaults: { _controller: MatrixAdminBundle:Manager:getPlants }

#Create new Plant
plant_form:
    path:     /plant/create
    defaults: { _controller: MatrixAdminBundle:Manager:createPlantForm }
    methods: GET

plant_create:
    path:     /plant/create
    defaults: { _controller: MatrixAdminBundle:Manager:createPlant }
    methods: POST

#Warehouses list
warehouses_list:
    path:     /manager/warehouses
    defaults: { _controller: MatrixAdminBundle:Manager:getWarehouses }

#Create new Warehouse
warehouse_form:
    path:     /warehouse/create
    defaults: { _controller: MatrixAdminBundle:Manager:createWarehouseForm }
    methods: GET

warehouse_create:
    path:     /warehouse/create
    defaults: { _controller: MatrixAdminBundle:Manager:createWarehouse }
    methods: POST

#Divisions list
divisions_list:
    path:     /manager/divisions
    defaults: { _controller: MatrixAdminBundle:Manager:getDivisions }

#Create new Division
division_form:
    path:     /division/create
    defaults: { _controller: MatrixAdminBundle:Manager:createDivisionForm }
    methods: GET

division_create:
    path:     /division/create
    defaults: { _controller: MatrixAdminBundle:Manager:createDivision }
    methods: POST

#Currencies list
currencies_list:
    path:     /manager/currencies
    defaults: { _controller: MatrixAdminBundle:Manager:getCurrencies }

#Create new Currency
currency_form:
    path:     /currency/create
    defaults: { _controller: MatrixAdminBundle:Manager:createCurrencyForm }
    methods: GET

currency_create:
    path:     /currency/create
    defaults: { _controller: MatrixAdminBundle:Manager:createCurrency }
    methods: POST

#Customers list
customers_list:
    path:     /manager/customers
    defaults: { _controller: MatrixAdminBundle:Manager:getCustomers }

#Create new Customer
customer_form:
    path:     /customer/create
    defaults: { _controller: MatrixAdminBundle:Manager:createCustomerForm }
    methods: GET

customer_create:
    path:     /customer/create
    defaults: { _controller: MatrixAdminBundle:Manager:createCustomer }
    methods: POST

#Units list
units_list:
    path:     /manager/units
    defaults: { _controller: MatrixAdminBundle:Manager:getUnits }

#Create new Unit
unit_form:
    path:     /unit/create
    defaults: { _controller: MatrixAdminBundle:Manager:createUnitForm }
    methods: GET

unit_create:
    path:     /unit/create
    defaults: { _controller: MatrixAdminBundle:Manager:createUnit }
    methods: POST

#Products list
products_list:
    path:     /manager/products
    defaults: { _controller: MatrixAdminBundle:Manager:getProducts }

#Create new Product
product_form:
    path:     /product/create
    defaults: { _controller: MatrixAdminBundle:Manager:createProductForm }
    methods: GET

product_create:
    path:     /product/create
    defaults: { _controller: MatrixAdminBundle:Manager:createProduct }
    methods: POST

#Services list
services_list:
    path:     /manager/services
    defaults: { _controller: MatrixAdminBundle:Manager:getServices }

#Create new Service
service_form:
    path:     /service/create
    defaults: { _controller: MatrixAdminBundle:Manager:createServiceForm }
    methods: GET

service_create:
    path:     /service/create
    defaults: { _controller: MatrixAdminBundle:Manager:createService }
    methods: POST

service_update_form:
    path:     /service/update/{id}
    defaults: { _controller: MatrixAdminBundle:Manager:updateServiceForm }
    methods: GET
    requirements:
            id: \d

service_update:
    path:     /service/update
    defaults: { _controller: MatrixAdminBundle:Manager:updateService }
    methods: POST

#ERROR 404
admin_404:
    path:     /{name}
    defaults: { _controller: MatrixAdminBundle:NotFound:index }
    requirements:
          name: ^(.*)$