
admin_login:
    path:      /login
    defaults:  { _controller: MatrixAdminBundle:Login:index }


admin_home:
    path:     /
    defaults: { _controller: MatrixAdminBundle:Index:index }

distributor_list:
    path:     /dist
    defaults: { _controller: MatrixAdminBundle:Index:index }

licenses_list:
    path:     /lic
    defaults: { _controller: MatrixAdminBundle:Licenses:index }

licenses_form:
    path:     /lic/create
    defaults: { _controller: MatrixAdminBundle:Licenses:createForm}
    methods: GET

licenses_create:
    path:     /lic/create
    defaults: {_controller: MatrixAdminBundle:Licenses:create}
    methods: POST

licenses_form_update:
    path: /lic/update/{id}
    defaults: {_controller: MatrixAdminBundle:Licenses:updateForm, id: 0}
    methods: GET

licenses_update:
    path: /lic/update/{id}
    defaults: {_controller: MatrixAdminBundle:Licenses:update, id: 0}
    methods: POST

distributor_form:
    path:     /dist/create
    defaults: { _controller: MatrixAdminBundle:Distributors:createForm }
    methods: GET

distributor_create:
    path:     /dist/create
    defaults: { _controller: MatrixAdminBundle:Distributors:create }
    methods: POST



#List of all Account Owners(Companies)
distributors_companies:
    path:     /comp
    defaults: { _controller: MatrixAdminBundle:Distributor:companies }


#DISTRIBUTOR
#Create new Account Owner(Company)
account_owner_form:
    path:     /owner/create
    defaults: { _controller: MatrixAdminBundle:Distributor:createAccountOwnerForm }
    methods: GET

account_owner_create:
    path:     /owner/create
    defaults: { _controller: MatrixAdminBundle:Distributor:createAccountOwner }
    methods: POST

#List of Account Owners created by this Distributor
account_owner_list:
    path:     /dist/owners
    defaults: { _controller: MatrixAdminBundle:Distributor:getAccountOwners }

#Licenses of this Distributor
distributors_licenses:
    path:     /dist/lic
    defaults: { _controller: MatrixAdminBundle:Licenses:getByDistributor }

#ACCOUNT OWNER
#Managers list
managers_list:
    path:     /owner/managers
    defaults: { _controller: MatrixAdminBundle:AccountOwner:getManagers }

#Create new Manager
manager_form:
    path:     /manager/create
    defaults: { _controller: MatrixAdminBundle:AccountOwner:createManagerForm }
    methods: GET

manager_create:
    path:     /manager/create
    defaults: { _controller: MatrixAdminBundle:AccountOwner:createManager }
    methods: POST

#########################################################################################
############                          MOBILE USER                         ###############
#########################################################################################
#Mobile Users list
mobile_users_list:
    path:     /manager/users
    defaults: { _controller: MatrixAdminBundle:MobileUser:getMobileUsers }

#Create new Mobile User
mobile_user_form:
    path:     /muser/create
    defaults: { _controller: MatrixAdminBundle:MobileUser:createMobileUserForm }
    methods: GET

mobile_user_create:
    path:     /muser/create
    defaults: { _controller: MatrixAdminBundle:MobileUser:createMobileUser }
    methods: POST

#########################################################################################
############                          DEPARTMENT                          ###############
#########################################################################################
#Update Mobile User
mobile_user_update_form:
    path: /muser/update/{id}
    defaults: { _controller: MatrixAdminBundle:Manager:updateMobileUserForm }
    methods: GET
    requirements:
              id: \d

mobile_user_update:
    path: /muser/update
    defaults: { _controller: MatrixAdminBundle:Manager:updateMobileUser }
    methods: POST

#Departments list
departments_list:
    path:     /manager/departments
    defaults: { _controller: MatrixAdminBundle:Department:getDepartments }

#Create new Department
department_form:
    path:     /department/create
    defaults: { _controller: MatrixAdminBundle:Department:createDepartmentForm }
    methods: GET


department_create:
    path:     /department/create
    defaults: { _controller: MatrixAdminBundle:Department:createDepartment }
    methods: POST

#########################################################################################
############                               PLANT                          ###############
#########################################################################################
#Update Department
department_update_form:
    path:     /department/update/{id}
    defaults: { _controller: MatrixAdminBundle:Manager:updateDepartmentForm}
    methods: GET
    requirements:
              id: \d

department_update:
    path:     /department/update
    defaults: { _controller: MatrixAdminBundle:Manager:updateDepartment}
    methods: POST

#Plants list
plants_list:
    path:     /manager/plants
    defaults: { _controller: MatrixAdminBundle:Plant:getPlants }

#Create new Plant
plant_form:
    path:     /plant/create
    defaults: { _controller: MatrixAdminBundle:Plant:createPlantForm }
    methods: GET

plant_create:
    path:     /plant/create
    defaults: { _controller: MatrixAdminBundle:Plant:createPlant }
    methods: POST

#Update Plant
plant_update_form:
    path:     /plant/update/{id}
    defaults: { _controller: MatrixAdminBundle:Manager:updatePlantForm }
    methods: GET
    requirements:
            id: \d

plant_update:
    path:     /plant/update
    defaults: { _controller: MatrixAdminBundle:Manager:updatePlant }
    methods: POST



#########################################################################################
############                           WAREHOUSE                          ###############
#########################################################################################
#Warehouses list
warehouses_list:
    path:     /manager/warehouses
    defaults: { _controller: MatrixAdminBundle:Warehouse:getWarehouses }

#Create new Warehouse
warehouse_form:
    path:     /warehouse/create
    defaults: { _controller: MatrixAdminBundle:Warehouse:createWarehouseForm }
    methods: GET

warehouse_create:
    path:     /warehouse/create
    defaults: { _controller: MatrixAdminBundle:Warehouse:createWarehouse }
    methods: POST

#########################################################################################
############                           DIVISION                           ###############
#########################################################################################
#Divisions list
divisions_list:
    path:     /manager/divisions
    defaults: { _controller: MatrixAdminBundle:Division:getDivisions }

#Create new Division
division_form:
    path:     /division/create
    defaults: { _controller: MatrixAdminBundle:Division:createDivisionForm }
    methods: GET

division_create:
    path:     /division/create
    defaults: { _controller: MatrixAdminBundle:Division:createDivision }
    methods: POST

#########################################################################################
############                           CURRENCY                           ###############
#########################################################################################
#Currencies list
currencies_list:
    path:     /manager/currencies
    defaults: { _controller: MatrixAdminBundle:Currency:getCurrencies }

#Create new Currency
currency_form:
    path:     /currency/create
    defaults: { _controller: MatrixAdminBundle:Currency:createCurrencyForm }
    methods: GET

currency_create:
    path:     /currency/create
    defaults: { _controller: MatrixAdminBundle:Currency:createCurrency }
    methods: POST

#########################################################################################
############                           CUSTOMER                           ###############
#########################################################################################
#Customers list
customers_list:
    path:     /manager/customers
    defaults: { _controller: MatrixAdminBundle:Customer:getCustomers }

#Create new Customer
customer_form:
    path:     /customer/create
    defaults: { _controller: MatrixAdminBundle:Customer:createCustomerForm }
    methods: GET

customer_create:
    path:     /customer/create
    defaults: { _controller: MatrixAdminBundle:Customer:createCustomer }
    methods: POST

#########################################################################################
############                            UNIT                              ###############
#########################################################################################
#Units list
units_list:
    path:     /manager/units
    defaults: { _controller: MatrixAdminBundle:Unit:getUnits }

#Create new Unit
unit_form:
    path:     /unit/create
    defaults: { _controller: MatrixAdminBundle:Unit:createUnitForm }
    methods: GET

unit_create:
    path:     /unit/create
    defaults: { _controller: MatrixAdminBundle:Unit:createUnit }
    methods: POST

#########################################################################################
############                        PRODUCTS                              ###############
#########################################################################################
#Products list
products_list:
    path:     /manager/products
    defaults: { _controller: MatrixAdminBundle:Product:getProducts }

#Create new Product
product_form:
    path:     /product/create
    defaults: { _controller: MatrixAdminBundle:Product:createProductForm }
    methods: GET

product_create:
    path:     /product/create
    defaults: { _controller: MatrixAdminBundle:Product:createProduct }
    methods: POST

#########################################################################################
############                        SERVICES                              ###############
#########################################################################################
#Services list
services_list:
    path:     /manager/services
    defaults: { _controller: MatrixAdminBundle:Service:getServices }

#Create new Service
service_form:
    path:     /service/create
    defaults: { _controller: MatrixAdminBundle:Service:createServiceForm }
    methods: GET

service_create:
    path:     /service/create
    defaults: { _controller: MatrixAdminBundle:Service:createService }
    methods: POST

service_update_form:
    path:     /service/update/{id}
    defaults: { _controller: MatrixAdminBundle:Service:updateServiceForm }
    methods: GET
    requirements:
            id: \d

service_update:
    path:     /service/update
    defaults: { _controller: MatrixAdminBundle:Service:updateService }
    methods: POST


#########################################################################################
############                             404                              ###############
#########################################################################################
#ERROR 404
admin_404:
    path:     /{name}
    defaults: { _controller: MatrixAdminBundle:NotFound:index }
    requirements:
          name: ^(.*)$