parameters:
#    matrix_service.example.class: Matrix\ServiceBundle\Example

services:
#    matrix_service.example:
#        class: %matrix_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
