matrix_service:
    resource: "@MatrixServiceBundle/Resources/config/routing.yml"
    prefix:   /mobile

login:
    path:      /login
    defaults:  { _controller: MatrixAdminBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

matrix_admin:
    resource: "@MatrixAdminBundle/Resources/config/routing.yml"
    prefix:   /



