security:
    firewalls:
        secured_area:
              pattern: ^/
              anonymous: ~
              form-login:
                      login_path: login
                      check_path: login_check
              logout:
                      path: /logout
                      target: /login

    access_control:
          - { path: ^/mobile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/mobile$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/dist/create, roles: [ROLE_ADMIN] }
          - { path: ^/dist/lic, roles: [ROLE_DISTRIBUTOR] }
          - { path: ^/lic, roles: [ROLE_ADMIN] }
          - { path: ^/dist, roles: [ROLE_ADMIN] }
          - { path: ^/, roles: [ROLE_ADMIN, ROLE_ACCOUNT_OWNER, ROLE_MANAGER, ROLE_DISTRIBUTOR] }
          - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # Include the following line to also secure the /admin path itself
     #    - { path: ^/$, roles: ROLE_ADMIN }

    providers:
          main:
              entity:
                    class: Matrix\AdminBundle\Entity\Users
                    property: email
      #  in_memory:
       #         memory:
        #              users:
         #                     ryan: { password: ryanpass, roles: 'ROLE_USER' }
          #                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
    encoders:
        Matrix\AdminBundle\Entity\Users:
                        algorithm: bcrypt
                        cost:      12
