service_login:
    path:       /login
    defaults:   { _controller: MatrixServiceBundle:Login:index }
    methods:    [POST]

service_logout:
    path:       /logout
    defaults:   { _controller: MatrixServiceBundle:Logout:index }
    methods:    [POST]

service_customers:
    path:       /customers
    defaults:   { _controller: MatrixServiceBundle:Customers:index }
    methods:    [POST]

service_customers_synch:
    path:       /customers/synch
    defaults:   { _controller: MatrixServiceBundle:Customers:synch }
    methods:    [POST]

service_items:
    path:       /items
    defaults:   { _controller: MatrixServiceBundle:Items:index }
    methods:    [POST]

service_orders_create:
    path:       /orders/create
    defaults:   { _controller: MatrixServiceBundle:Orders:index }
    methods:    [POST]

service_dispatches_create:
    path:       /dispatches/create
    defaults:   { _controller: MatrixServiceBundle:Dispatches:index }
    methods:    [POST]

service_invoices_create:
    path:       /invoices/create
    defaults:   { _controller: MatrixServiceBundle:Invoices:index }
    methods:    [POST]

service_synch:
    path:       /synchronize
    defaults:   { _controller: MatrixServiceBundle:Synch:index }
    methods:    [POST]

###############################################################################
####################              TEST                      ###################
###############################################################################

test_all:
    path:       /test
    defaults:   { _controller: MatrixServiceBundle:Test:testAll }
    methods:    [GET]

test_ccpayment:
    path:       /test/ccpayment
    defaults:   { _controller: MatrixServiceBundle:Test:testCCPayment }
    methods:    [GET]

test_bondpayment:
    path:       /test/bond_payment
    defaults:   { _controller: MatrixServiceBundle:Test:testBondPayment }
    methods:    [GET]

test_chequepayment:
    path:       /test/cheque_payment
    defaults:   { _controller: MatrixServiceBundle:Test:testChequePayment }
    methods:    [GET]

test_cashpayment:
    path:       /test/cash_payment
    defaults:   { _controller: MatrixServiceBundle:Test:testCashPayment }
    methods:    [GET]

service_404_1:
    path:     /
    defaults: { _controller: MatrixServiceBundle:NotFound:index }

service_404:
    path:     /{name}
    defaults: { _controller: MatrixServiceBundle:NotFound:index }
    requirements:
          name: ^(.*)$
